declare @funcional        varchar(50) = 'T02348'

-- TRECHO DAS REGRAS DE USUÁRIO
--if (@tipo_atualizacao = 2 or @tipo_atualizacao = 4)
--begin
      delete corp_usuario_regra
      where cd_usuario = @funcional

insert corp_usuario_regra (cd_usuario, cd_regra, dv_regra, vl_regra) values (@funcional, 8,1, convert(varchar(50),9999999999))
insert corp_usuario_regra (cd_usuario, cd_regra, dv_regra, vl_regra) values (@funcional, 44,1, convert(varchar(50),200000))
insert corp_usuario_regra (cd_usuario, cd_regra, dv_regra, vl_regra) values (@funcional, 45,1, convert(varchar(50),NULL))
insert corp_usuario_regra (cd_usuario, cd_regra, dv_regra, vl_regra) values (@funcional, 47,1, convert(varchar(50),NULL))
insert corp_usuario_regra (cd_usuario, cd_regra, dv_regra, vl_regra) values (@funcional, 59,1, convert(varchar(50),500))
insert corp_usuario_regra (cd_usuario, cd_regra, dv_regra, vl_regra) values (@funcional, 226,1, convert(varchar(50),NULL))
--insert corp_usuario_regra (cd_usuario, cd_regra, dv_regra, vl_regra) values (@funcional, 228,1, convert(varchar(50),NULL))
insert corp_usuario_regra (cd_usuario, cd_regra, dv_regra, vl_regra) values (@funcional, 235,1, convert(varchar(50),NULL))
insert corp_usuario_regra (cd_usuario, cd_regra, dv_regra, vl_regra) values (@funcional, 236,1, convert(varchar(50),NULL))
insert corp_usuario_regra (cd_usuario, cd_regra, dv_regra, vl_regra) values (@funcional, 238,1, convert(varchar(50),NULL))
insert corp_usuario_regra (cd_usuario, cd_regra, dv_regra, vl_regra) values (@funcional, 240,1, convert(varchar(50),NULL))
insert corp_usuario_regra (cd_usuario, cd_regra, dv_regra, vl_regra) values (@funcional, 243,1, convert(varchar(50),1))
insert corp_usuario_regra (cd_usuario, cd_regra, dv_regra, vl_regra) values (@funcional, 245,1, convert(varchar(50),NULL))
insert corp_usuario_regra (cd_usuario, cd_regra, dv_regra, vl_regra) values (@funcional, 252,1, convert(varchar(50),NULL))
insert corp_usuario_regra (cd_usuario, cd_regra, dv_regra, vl_regra) values (@funcional, 258,1, convert(varchar(50),NULL))
insert corp_usuario_regra (cd_usuario, cd_regra, dv_regra, vl_regra) values (@funcional, 264,1, convert(varchar(50),NULL))
insert corp_usuario_regra (cd_usuario, cd_regra, dv_regra, vl_regra) values (@funcional, 275,1, convert(varchar(50),999999999))
insert corp_usuario_regra (cd_usuario, cd_regra, dv_regra, vl_regra) values (@funcional, 276,1, convert(varchar(50),99999999))
insert corp_usuario_regra (cd_usuario, cd_regra, dv_regra, vl_regra) values (@funcional, 283,1, convert(varchar(50),NULL))
insert corp_usuario_regra (cd_usuario, cd_regra, dv_regra, vl_regra) values (@funcional, 309,1, convert(varchar(50),NULL))
insert corp_usuario_regra (cd_usuario, cd_regra, dv_regra, vl_regra) values (@funcional, 319,1, convert(varchar(50),NULL))
insert corp_usuario_regra (cd_usuario, cd_regra, dv_regra, vl_regra) values (@funcional, 328,1, convert(varchar(50),NULL))
insert corp_usuario_regra (cd_usuario, cd_regra, dv_regra, vl_regra) values (@funcional, 333,1, convert(varchar(50),100))
insert corp_usuario_regra (cd_usuario, cd_regra, dv_regra, vl_regra) values (@funcional, 334,1, convert(varchar(50),NULL))
insert corp_usuario_regra (cd_usuario, cd_regra, dv_regra, vl_regra) values (@funcional, 341,1, convert(varchar(50),NULL))
insert corp_usuario_regra (cd_usuario, cd_regra, dv_regra, vl_regra) values (@funcional, 347,1, convert(varchar(50),NULL))
insert corp_usuario_regra (cd_usuario, cd_regra, dv_regra, vl_regra) values (@funcional, 349,1, convert(varchar(50),15))
insert corp_usuario_regra (cd_usuario, cd_regra, dv_regra, vl_regra) values (@funcional, 350,0, convert(varchar(50),NULL))
insert corp_usuario_regra (cd_usuario, cd_regra, dv_regra, vl_regra) values (@funcional, 353,1, convert(varchar(50),15))
insert corp_usuario_regra (cd_usuario, cd_regra, dv_regra, vl_regra) values (@funcional, 359,1, convert(varchar(50),NULL))
insert corp_usuario_regra (cd_usuario, cd_regra, dv_regra, vl_regra) values (@funcional, 360,1, convert(varchar(50),NULL))
insert corp_usuario_regra (cd_usuario, cd_regra, dv_regra, vl_regra) values (@funcional, 366,1, convert(varchar(50),NULL))
insert corp_usuario_regra (cd_usuario, cd_regra, dv_regra, vl_regra) values (@funcional, 373,1, convert(varchar(50),NULL))
insert corp_usuario_regra (cd_usuario, cd_regra, dv_regra, vl_regra) values (@funcional, 381,1, convert(varchar(50),NULL))
insert corp_usuario_regra (cd_usuario, cd_regra, dv_regra, vl_regra) values (@funcional, 386,1, convert(varchar(50),NULL))
insert corp_usuario_regra (cd_usuario, cd_regra, dv_regra, vl_regra) values (@funcional, 392,1, convert(varchar(50),NULL))
insert corp_usuario_regra (cd_usuario, cd_regra, dv_regra, vl_regra) values (@funcional, 397,1, convert(varchar(50),NULL))
insert corp_usuario_regra (cd_usuario, cd_regra, dv_regra, vl_regra) values (@funcional, 400,1, convert(varchar(50),NULL))
insert corp_usuario_regra (cd_usuario, cd_regra, dv_regra, vl_regra) values (@funcional, 401,1, convert(varchar(50),NULL))
insert corp_usuario_regra (cd_usuario, cd_regra, dv_regra, vl_regra) values (@funcional, 412,1, convert(varchar(50),NULL))
insert corp_usuario_regra (cd_usuario, cd_regra, dv_regra, vl_regra) values (@funcional, 416,1, convert(varchar(50),NULL))
insert corp_usuario_regra (cd_usuario, cd_regra, dv_regra, vl_regra) values (@funcional, 449,1, convert(varchar(50),NULL))
insert corp_usuario_regra (cd_usuario, cd_regra, dv_regra, vl_regra) values (@funcional, 451,1, convert(varchar(50),NULL))
insert corp_usuario_regra (cd_usuario, cd_regra, dv_regra, vl_regra) values (@funcional, 471,1, convert(varchar(50),NULL))
insert corp_usuario_regra (cd_usuario, cd_regra, dv_regra, vl_regra) values (@funcional, 487,1, convert(varchar(50),NULL))
insert corp_usuario_regra (cd_usuario, cd_regra, dv_regra, vl_regra) values (@funcional, 488,1, convert(varchar(50),NULL))
insert corp_usuario_regra (cd_usuario, cd_regra, dv_regra, vl_regra) values (@funcional, 489,1, convert(varchar(50),NULL))
insert corp_usuario_regra (cd_usuario, cd_regra, dv_regra, vl_regra) values (@funcional, 494,1, convert(varchar(50),NULL))
insert corp_usuario_regra (cd_usuario, cd_regra, dv_regra, vl_regra) values (@funcional, 497,1, convert(varchar(50),NULL))
insert corp_usuario_regra (cd_usuario, cd_regra, dv_regra, vl_regra) values (@funcional, 512,1, convert(varchar(50),NULL))
insert corp_usuario_regra (cd_usuario, cd_regra, dv_regra, vl_regra) values (@funcional, 513,1, convert(varchar(50),NULL))
insert corp_usuario_regra (cd_usuario, cd_regra, dv_regra, vl_regra) values (@funcional, 514,1, convert(varchar(50),NULL))
insert corp_usuario_regra (cd_usuario, cd_regra, dv_regra, vl_regra) values (@funcional, 515,1, convert(varchar(50),NULL))
insert corp_usuario_regra (cd_usuario, cd_regra, dv_regra, vl_regra) values (@funcional, 582,1, convert(varchar(50),NULL))
insert corp_usuario_regra (cd_usuario, cd_regra, dv_regra, vl_regra) values (@funcional, 583,1, convert(varchar(50),NULL))
insert corp_usuario_regra (cd_usuario, cd_regra, dv_regra, vl_regra) values (@funcional, 585,1, convert(varchar(50),NULL))
insert corp_usuario_regra (cd_usuario, cd_regra, dv_regra, vl_regra) values (@funcional, 586,1, convert(varchar(50),NULL))

      print 'ATUALIZAÇÃO: Atualização Regras de Usuário Executada'

--end